### ISSUE TITLE
Entity name on a dashboard page

### ISSUE THREAD

**Issue by meanin** [meanin/candidate-evaluator#43]
![image](https://user-images.githubusercontent.com/6974668/49922336-b047e100-feb0-11e8-93a3-55e45294d193.png)

**Comment by devmonte** [comment]
Actually, `RecentActivityEntity` doesn't have a field `Name`. I will add it but what value should it hold? Name of the category/question or name od the operation?

**Comment by devmonte** [comment]
Nevermind :D
